In [1]:
import numpy as np
import random

In [2]:
#create d dimensional array ndarray 
#using np.array()
data = np.array([[1.5, -0.1,3], [0, -3, 6.5]],np.float64) #or dtype=int64) #list size should be same for all else error
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [3]:
#characteristics
#.shape --- a tuple indicating the rows*column
#.dtype --- an object describing the data type of the array
#.ndim --- retuns the no. of rows
data.shape, data.dtype, data.ndim

((2, 3), dtype('float64'), 2)

In [4]:
#all the ways to create an array:
#array	Convert input data (list, tuple, array, or other sequence type) to an ndarray #np.array(shape,dtype=None)
#asarray	Convert input to ndarray, but do not copy if the input is already an ndarray
#arange	Like the built-in range but returns an ndarray instead of a list (a range kinda) #np.arange(i)
#ones	Produce an array of all 1s with the given shape and data type #numpy.ones(shape, dtype=None)
#ones_like	ones_like takes another array and produces a ones array of the same shape and data type #numpy.ones_like(a, dtype=None)
#zeros, zeros_like	Like ones and ones_like but producing arrays of 0s instead
#empty, empty_like	Create new arrays without initializing entries, numpy.empty(shape, dtype=float) numpy.empty_like(prototype, dtype=None)
#full	Produce an array of the given shape values set to "fill value".#np.full(shape, fill_value, dtype=None)
#full_like	 like ones_like with a fill value #numpy.full_like(a, fill_value, dtype=None)
#identity	Identity matrix np.identity(n, dtype=None)

In [5]:
print(np.arange(5))

[0 1 2 3 4]


In [6]:
x= np.ones((3,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
print(np.ones_like(x))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
#eye	Create a matrix with 1s on the diagonal and 0s elsewhere 
#np.eye(N, M=None, k=0, dtype=<class 'float'>)
#M(int, optional)Number of columns in the output. If None, defaults to N.

In [10]:
print(np.eye(4,M=3,k=0))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [11]:
#astype to specifically convert the dtype of array

In [12]:
arr = np.array([1, 2, 3, 4, 5])
float_arr = arr.astype(np.float64)

In [13]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [14]:
#slicing,indexing works the same way as lists
# one thing to remember is slicing does not create a new object. so any changes to slice aslo change the original array

In [15]:
arr = np.arange(10)
print(arr)
arr_slice = arr[5:8]
arr_slice[:] = 64
print(arr)
#expicitly use .copy() to make a copy

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 64 64 64  8  9]


In [16]:
#For 2d, axis 0 (first number) as the "rows" of the array and axis 1 (second number) as the "columns."

In [17]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr2d[0][2]

3

In [19]:
# you can pass a comma-separated list of indices to select individual elements. doesn't work with nested lists
arr2d[0,2]

3

In [20]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [21]:
lower_dim_slice = arr2d[1, :2]
print(lower_dim_slice)
print(lower_dim_slice.shape)

[4 5]
(2,)


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d.shape

(2, 2, 3)

In [23]:
arr3d[1, 0]

array([7, 8, 9])

In [24]:
y=arr2d[:, :1]
print(y)
print(y.shape)
print(y.T)

[[1]
 [4]
 [7]]
(3, 1)
[[1 4 7]]


In [25]:
y=arr2d[:, 0]
print(y)
print(y.shape)

[1 4 7]
(3,)


In [26]:
#boolean indexing
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])
#comparisons (such as ==) with arrays are also arrays (boolean).
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [27]:
#This Boolean array can be passed when indexing the array:
data[names=='Bob']

array([[4, 7],
       [0, 0]])

In [28]:
#The Boolean array must be of the same length as the array axis it’s indexing.
#also select from the rows where names == "Bob" and index the columns, too
data[names == "Bob", 1]

array([7, 0])

In [29]:
#to select everything but "Bob" you can either use != or negate the condition using ~
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [30]:
~(names == 'Bob')

array([False,  True,  True, False,  True,  True,  True])

In [31]:
data[~(names == 'Bob')]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [32]:
#To select two of the three names to combine multiple Boolean conditions,
#use Boolean arithmetic operators like & (and) and | (or) (python functions and or doesnot work)
mask = (names=='Bob') | (names=='Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [33]:
#Boolean indexing and assigning the result to a new variable always creates a copy of the data.
data[data < 0] = 0
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [34]:
#.reshape() to reshape the array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [35]:
#you do not have to specify an exact number for one of the dimensions in the reshape method.
#Pass -1 as the value, and NumPy will calculate this number for you.
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [36]:
#Flattening array (reshape(-1)) means converting a multidimensional array into a 1D array.
newarr = arr.reshape(-1)
newarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [37]:
# .T to transpose the array
arr = np.arange(15).reshape((3, 5))
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [38]:
# np.dot(array1,array2) to calaculate the inner product

In [39]:
# also @ to matrix multiplication
arr.T@arr

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [40]:
#random array generator
rng=np.random.default_rng()
type(rng)
#these are pseudorandom as fixing the seed will give same no. always say .default_rng(seed=100)

numpy.random._generator.Generator

In [41]:
print(rng.random()) #generate random floating-point numbers in the range [0.0, 1.0)
print(rng.standard_normal()) #Draw samples from a standard normal distribution
print(rng.uniform()) #Draw samples from a uniform distribution #has low and high parameters #rng.uniform(low=0, high=1)
print(rng.integers(5)) #Draw random integers from a given low-to-high range #rng.integers(low) #chuityaap h bada

0.23036737824150233
-0.23877987101927312
0.6163366310817505
4


In [42]:
print(rng.random((5, 3)))
print(rng.integers(size=(2, 3), low=1, high=5))
print(rng.uniform(size=(2, 3), low=1, high=5))
print(rng.standard_normal(size=(2, 3)))

[[0.64242066 0.43129027 0.06757685]
 [0.854047   0.29206288 0.83448988]
 [0.11782223 0.78098907 0.08793032]
 [0.98004916 0.04448735 0.83934063]
 [0.90747935 0.65165656 0.61615831]]
[[3 2 3]
 [2 2 3]]
[[2.91677734 1.32070284 2.82618755]
 [1.95724738 4.01739049 3.99812239]]
[[-0.23148799  0.64762401  0.15652818]
 [ 0.73003559  0.50497233 -0.46379014]]


In [43]:
#universal functions
arr = np.arange(10)
print(np.sqrt(arr)) #square root of array
print(np.exp(arr)) #exponantial of array
x = rng.standard_normal(8)
y = rng.standard_normal(8)
print(np.maximum(x, y))
#interesting one
arr= np.array([ 4.5146, -8.1079, -0.7909,  2.2474, -6.718 , -0.4084,  8.6237])
remainder, whole_part = np.modf(arr) #create 2 arrays one with intergers and other with fractional value


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[ 1.0288495   0.7658638   1.71490866 -0.34305128  1.21368288  0.50967038
 -0.27165497  0.42740796]


In [44]:
#Expressing Conditional Logic
#.where() (Important function)


In [45]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
x=[]
for i,j in enumerate(cond):
    if j:
        x.append(xarr[i])
    else:
        x.append(yarr[i])
print(x)
#or
[xarr[i] if j else yarr[i] for i,j in enumerate(cond)]
#or
[(x if c else y) for x,y,c in zip(xarr,yarr,cond)] #ingenious
        

[1.1, 2.2, 1.3, 1.4, 2.5]


[1.1, 2.2, 1.3, 1.4, 2.5]

In [46]:
r = np.where(cond, xarr, yarr) #simple #cond must be boolean
r

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [47]:
#syntax numpy.where(condition, x, y) #x if true and y if false 
#condition array_like, bool Where True, yield x, otherwise yield y.
#x, y array_like
print(np.where([[True, False], [True, True]],
         [[1, 2], [3, 4]],
         [[9, 8], [7, 6]]))

[[1 8]
 [3 4]]


In [48]:
arr = rng.standard_normal((4, 4))
np.where(arr>0,2,-2)

array([[-2, -2, -2,  2],
       [-2, -2, -2, -2],
       [ 2, -2, -2, -2],
       [-2,  2, -2, -2]])

In [49]:
#mathematical and statistical methods
arr= rng.integers(size=(5,4),low=1,high=5)
print(arr)
print(arr.mean())
print(arr.sum())
print(np.mean(arr))

[[1 2 1 3]
 [4 3 2 3]
 [4 4 4 2]
 [3 1 3 3]
 [1 3 4 4]]
2.75
55
2.75


In [50]:
#Functions like mean and sum take an optional axis argument that computes the statistic over the given axis,
#resulting in an array with one less dimension
print(arr.sum(axis=0)) #arr.sum(axis=0) means "compute sum down the rows."
print(arr.sum(axis=1)) #arr.sum(axis=1) means "compute mean across the columns,"

[13 13 14 15]
[ 7 12 14 10 12]


In [51]:
print(arr.cumsum())
print(arr.cumsum(axis=0))
print(arr.cumsum(axis=1))

[ 1  3  4  7 11 14 16 19 23 27 31 33 36 37 40 43 44 47 51 55]
[[ 1  2  1  3]
 [ 5  5  3  6]
 [ 9  9  7  8]
 [12 10 10 11]
 [13 13 14 15]]
[[ 1  3  4  7]
 [ 4  7  9 12]
 [ 4  8 12 14]
 [ 3  4  7 10]
 [ 1  4  8 12]]


In [52]:
#other mathematical functions
#std, var	Standard deviation and variance, respectively
#min, max	Minimum and maximum
#argmin, argmax	Indices of minimum and maximum elements, respectively
#cumprod	Cumulative product of elements starting from 1

In [53]:
#another use of sum
#sum is often used as a means of counting True values in a Boolean array:
arr = rng.standard_normal(100)
(arr > 0).sum() # Number of positive values

51

In [54]:
bools = np.array([False, False, True, False])
bools.any(),bools.all()


(True, False)

In [61]:
#sorting in numpy
q = rng.standard_normal((5, 3))
q

array([[-0.31327067, -0.85809795,  1.05872773],
       [ 0.58171327, -0.22109866, -0.64061888],
       [-1.10241692, -0.93941873,  0.4425667 ],
       [-1.64368274, -0.24029416,  1.06910617],
       [ 1.30373098, -0.20367402,  1.10501291]])

In [64]:
q.sort(axis=0)
q

array([[-1.64368274, -0.93941873, -0.64061888],
       [-1.10241692, -0.85809795,  0.4425667 ],
       [-0.31327067, -0.24029416,  1.05872773],
       [ 0.58171327, -0.22109866,  1.06910617],
       [ 1.30373098, -0.20367402,  1.10501291]])

In [66]:
q.sort(axis=1)
q

array([[-1.64368274, -0.93941873, -0.64061888],
       [-1.10241692, -0.85809795,  0.4425667 ],
       [-0.31327067, -0.24029416,  1.05872773],
       [-0.22109866,  0.58171327,  1.06910617],
       [-0.20367402,  1.10501291,  1.30373098]])

In [67]:
#save and load array
arr = np.arange(10)
np.save("some_array", arr)
np.load("some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
# Random walk code
import random
position = 0
walk = [position]
nsteps = 1000
for _ in range(nsteps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)
print(walk)

[0, -1, -2, -1, 0, -1, 0, 1, 0, -1, -2, -1, 0, -1, -2, -1, 0, -1, -2, -1, -2, -3, -2, -1, 0, 1, 0, 1, 0, 1, 0, 1, 0, -1, 0, 1, 2, 1, 2, 3, 4, 5, 6, 5, 4, 3, 4, 5, 6, 7, 6, 5, 4, 5, 4, 3, 4, 5, 6, 5, 4, 3, 2, 3, 2, 3, 4, 3, 2, 3, 4, 5, 6, 7, 8, 7, 6, 7, 6, 7, 6, 5, 6, 5, 6, 5, 6, 5, 4, 3, 4, 5, 4, 3, 2, 1, 2, 1, 0, -1, -2, -3, -2, -3, -4, -5, -4, -3, -2, -3, -2, -3, -4, -3, -2, -3, -2, -1, -2, -1, 0, 1, 0, -1, 0, -1, 0, 1, 2, 3, 4, 5, 4, 3, 4, 3, 4, 3, 2, 3, 2, 1, 0, -1, -2, -3, -4, -5, -4, -5, -4, -3, -2, -3, -2, -3, -2, -3, -4, -3, -2, -3, -4, -3, -2, -1, -2, -3, -2, -3, -2, -3, -2, -1, -2, -3, -2, -3, -4, -5, -4, -3, -2, -3, -4, -3, -2, -3, -2, -3, -4, -5, -4, -5, -6, -5, -4, -3, -2, -3, -4, -5, -4, -5, -4, -5, -6, -7, -8, -7, -6, -7, -8, -9, -10, -9, -8, -9, -10, -9, -8, -9, -8, -7, -8, -7, -8, -7, -6, -7, -6, -7, -6, -5, -4, -5, -6, -7, -6, -5, -4, -3, -2, -1, -2, -1, 0, -1, -2, -3, -2, -3, -4, -5, -4, -5, -4, -5, -4, -3, -4, -3, -2, -3, -2, -3, -2, -3, -2, -3, -2, -3, -4, -5, -6, 